This is makeindex, version 2.16 [MiKTeX 25.4].
Scanning style file ./thesis.ist...........................done (27 attributes redefined, 0 ignored).
Scanning input file thesis.acn....done (62 entries accepted, 0 rejected).
Sorting entries....done (364 comparisons).
Generating output file thesis.acr....done (52 lines written, 0 warnings).
Output written in thesis.acr.
Transcript written in thesis.alg.
