clc
addpath("C:\Users\u0138258\Documents\thesis-latex\figures of matlab");

myPDFSavePath="C:\Users\u0138258\Documents\thesis-latex\figures of matlab\s6 experimental\pdf";
%% svd of modal parameters
Line_color1=parula80(2);

fig1="C:\Users\u0138258\Documents\thesis-latex\figures of matlab\s6 experimental\fig\sdv of modal parameters due to cable attachment.fig";
Figure_Styling_Iman_Manuscript(fig1,...
    General_ShowFigure='visible',...
    General_SavePDF="",...
    General_SavePath=myPDFSavePath,...
    SizeAndPos_heightCm=(9/16)*13,...
    SizeAndPos_widthCm=13,...
    Legend_OnOff="on",...
    Legend_Strings=["Modal frequency","Modal damping"],...
    Legend_Location="northeast",...
    Axis_YLim=[],...
    Axis_XLim=[],...
    Line_color=Line_color1,...
    Line_markerFaceColor=Line_color1,...
    Line_markerFreqRatio=5);
figH=gcf;
ax=gca;

ax.Legend.Position(1)=ax.Legend.Position(1)-30;
ax.Legend.Position(2)=ax.Legend.Position(2);

%Fix the errorbar line width
yyaxis(ax, 'left');           % Activate left side
e_left = get(ax, 'Children'); % Get all objects on this side
e_left.Color=Line_color1(1,:);
e_left.MarkerEdgeColor=Line_color1(1,:);
% e_left.MarkerFaceColor=Line_color1(1,:);
e_left = findobj(e_left, 'Type', 'ErrorBar'); 
set(e_left, 'LineWidth', 1);

% --- Fix Right Side ---
yyaxis(ax, 'right');           % Activate right side
e_right = get(ax, 'Children'); % Get objects on this side
e_right.Color=Line_color1(2,:);
e_right.MarkerEdgeColor=Line_color1(2,:);
% e_right.MarkerFaceColor=Line_color1(2,:);
e_right = findobj(e_right, 'Type', 'ErrorBar');
set(e_right, 'LineWidth', 1);


exportgraphics(figH,fullfile(myPDFSavePath,strcat('Figure_',"sdvOfModalParameters", ...
    string(datetime('now','Format','yyyyMMdd_HHmmss')),'.pdf')),'ContentType', 'vector');
%% Figure with subplots measModalParamDiffs1D3D
Line_color1=parula80(5);
fig2="C:\Users\u0138258\Documents\thesis-latex\figures of matlab\s6 experimental\fig\measModalParamDiffs1D3D.fig";

Figure_Styling_Iman_Manuscript_Subplots(fig2,...
    General_ShowFigure='visible',...
    General_SavePDF="",...
    SizeAndPos_heightCm=14,...
    SizeAndPos_widthCm=14.5,...
    Legend_OnOff=["off", "off","off","on"],...  % legend only on 1st subplot
    Legend_Strings={[],[],[],["0-0","1-1","1-2","2-1","2-2"]},...  % cell array for per-subplot legends
    TitleLabel_YlabelText=[],...
    Axis_YLim={},...  % different Y limits per subplot
    Axis_XLim=[1 6],...  % same X limit for all (not a cell = applies to all)
    Axis_XMinorTick="off",...
    Line_color=Line_color1, ...
    Axis_GridStyle="-",...
    Axis_LineWidth=2,...
    Line_marker=[">","<","v","^","x"],...
    Line_style=["-","-.",":","--","-"],...
    Line_markerFaceColor=Line_color1,...
    Line_markerFreqRatio=5);
figH=gcf;
myax=figH.Children;
myax(2).YLabel.String="Modal damping coefficient - 3D";   
myax(4).YLabel.String={'Modal frequency differece ';'vs. the bare plate - 3D'}; 
myax(6).YLabel.String="Modal damping coefficient - 1D";   
myax(8).YLabel.String={'Modal frequency differece ';'vs. the bare plate - 1D'}; 
myax(1).Location="southeast";
myax(1).Position(1)=myax(1).Position(1)+3;

exportgraphics(figH,fullfile(myPDFSavePath,strcat('Figure_',"measModalParamDiffs1D3D", ...
    string(datetime('now','Format','yyyyMMdd_HHmmss')),'.pdf')),'ContentType', 'vector');


%% validation1
Line_color1=parula80(3);
Line_color1=[Line_color1;Line_color1];
% Line_color1=[Line_color1(1:2,:);Line_color1(1:2,:);Line_color1(3,:)]; %because quantitise are similar 
fig3="C:\Users\u0138258\Documents\thesis-latex\figures of matlab\s6 experimental\fig\validation1.fig";

Figure_Styling_Iman_Manuscript_Subplots(fig3,...
    General_ShowFigure='visible',...
    General_SavePDF="",...
    SizeAndPos_heightCm=10.5,...
    SizeAndPos_widthCm=14.5,...
    Legend_OnOff=["on"],...  % legend only on 1st subplot
    Legend_Strings=[],...
    TitleLabel_YlabelText=[],...
    Axis_YLim=[-6,0.1],...  % different Y limits per subplot
    Axis_XLim=[1 6],...  % same X limit for all (not a cell = applies to all)
    Axis_XMinorTick="off",...
    Line_color=Line_color1, ...
    Axis_GridStyle="-",...
    Axis_LineWidth=2,...
    Line_marker=["square","o","x","square","o","x"],...
    Line_style=["--","--","--","-","-","-"],...
    Line_markerFaceColor=Line_color1,...
    Line_markerFreqRatio=5);
figH=gcf;
yyaxis right
ylim([-0.1e-3 6e-3]) % to make we see the line at 0, stupid bug
exportgraphics(figH,fullfile(myPDFSavePath,strcat('Figure_',"validation1", ...
    string(datetime('now','Format','yyyyMMdd_HHmmss')),'.pdf')),'ContentType', 'vector');

%% diffAccFRF
Line_color1=parula80(6);
fig4="C:\Users\u0138258\Documents\thesis-latex\figures of matlab\s6 experimental\fig\diffAccFRF.fig";

Figure_Styling_Iman_Manuscript_Subplots(fig4,...
    General_ShowFigure='visible',...
    General_SavePDF="",...
    SizeAndPos_heightCm=15,...
    SizeAndPos_widthCm=14.5,...
    Legend_OnOff=["on"],...  % legend only on 1st subplot
    Legend_Strings=[],...
    TitleLabel_YlabelText=[],...
    Axis_YLim=[],...  % different Y limits per subplot
    Axis_XLim=[],...  % same X limit for all (not a cell = applies to all)
    Axis_XMinorTick="off",...
    Line_color=Line_color1, ...
    Axis_GridStyle="-",...
    Axis_LineWidth=2,...
    Line_marker=["none","<","o","square","none","none"],...
    Line_style=["-.","-.","-.","-.","-","-"],...
    Line_width=[2,2,2,2,6,6],...
    Line_markerFaceColor=Line_color1,...
    Line_markerFreqRatio=40);
figH=gcf;
ax=gca;
h = findobj(ax, 'Type', 'line');
for i = 1:length(h)
    if i <= 6
        
        QWE=50; %frequency of the markers for non-equidistant xdatas
        r1=h(i).XData(1):((h(i).XData(end)-h(i).XData(1))/QWE):h(i).XData(end);
        gg=zeros(size(r1));
        for j=1:length(r1)
            [~,gg(j)]=min(abs(h(i).XData-r1(j)));
        end
        set(h(i), 'MarkerIndices', gg);
        w(i,:)=1:fix(length(h(i).XData)/40):length(h(i).XData);
        e(i,:)=h(i).XData(w(i,:));
    end
end
legend('Location','southwest')
exportgraphics(figH,fullfile(myPDFSavePath,strcat('Figure_',"diffAccFRF_", ...
    string(datetime('now','Format','yyyyMMdd_HHmmss')),'.pdf')),'ContentType', 'vector');

%% validation2
Line_color1=parula80(3);
Line_color1=[Line_color1;Line_color1];
% Line_color1=[Line_color1(1:2,:);Line_color1(1:2,:);Line_color1(3,:)]; %because quantitise are similar 
fig3="C:\Users\u0138258\Documents\thesis-latex\figures of matlab\s6 experimental\fig\validation2.fig";

Figure_Styling_Iman_Manuscript_Subplots(fig3,...
    General_ShowFigure='visible',...
    General_SavePDF="",...
    SizeAndPos_heightCm=10.5,...
    SizeAndPos_widthCm=14.5,...
    Legend_OnOff=["on"],...  % legend only on 1st subplot
    Legend_Strings=[],...
    TitleLabel_YlabelText=[],...
    Axis_YLim=[-9,0.1],...  % different Y limits per subplot
    Axis_XLim=[1 6],...  % same X limit for all (not a cell = applies to all)
    Axis_XMinorTick="off",...
    Line_color=Line_color1, ...
    Axis_GridStyle="-",...
    Axis_LineWidth=2,...
    Line_marker=["square","o","x","square","o","x"],...
    Line_style=["--","--","--","-","-","-"],...
    Line_markerFaceColor=Line_color1,...
    Line_markerFreqRatio=5);
figH=gcf;
yyaxis right
ylim([-0.1e-3 9e-3]) % to make we see the line at 0, stupid bug
legend('Location','south')
exportgraphics(figH,fullfile(myPDFSavePath,strcat('Figure_',"validation2", ...
    string(datetime('now','Format','yyyyMMdd_HHmmss')),'.pdf')),'ContentType', 'vector');


%%

% %%%%From here on out it's from previous stuff!
% %% force and RPM profile fig
% Line_color1=parula80(4);
% % Line_color1=parula(4);
% 
% fig1="C:\G\Academic\University\Ph.D (leuven)\2024\2.15 MSSP paper\Matlab plots for paper\Figs\force_and_rpm_profile2.fig";
% Figure_Styling_Iman_MSSP(fig1,...
%     General_ShowFigure='visible',...
%     General_SavePDF="",...
%     General_SavePath="C:\G\Academic\University\Ph.D (leuven)\2024\2.15 MSSP paper\Matlab plots for paper\Pdfs",...
%     SizeAndPos_heightCm=6,...
%     SizeAndPos_widthCm=9.5,...
%     Legend_OnOff="on",...
%     Legend_Strings=["Measured force","Nominal force","Measured shaft speed","Nominal shaft speed"],...
%     Legend_Location="southeast",...
%     Axis_YLim=[],...
%     Axis_XLim=[0 202],...
%     Line_style=["-","-","-","-"],...
%     Line_width=[2 1 2 1],...
%     Line_color=Line_color1,...
%     Line_markerFaceColor=Line_color1,...
%     Line_marker=["^","none","o","none"],...
%     Line_markerFreqRatio=5);
% 
% legend('Orientation','horizontal')
% legend('hide')
% 
% yyaxis left
% axH=gca;
% axH.YLabel.String="Force [kN]";
% axH.XLabel.String="Time [s]";
% 
% yyaxis right
% figH=gcf;
% axH=gca;
% axH.YLabel.String="Shaft speed [rev/min]";
% axH.YLim=[4000 6000];
% 
% exportgraphics(gcf,fullfile("C:\G\Academic\University\Ph.D (leuven)\2024\2.15 MSSP paper\Matlab plots for paper\Pdfs"...
%     ,strcat('Figure_',"force_and_rpm_profile",string(datetime('now','Format','yyyyMMdd_HHmmss')),'.pdf')),'ContentType', 'vector');
% 
% %Just the legend of the figure
% legend('show')
% allLineHandles = findall(gcf, 'type','line');
% for i = 1:length(allLineHandles)
%     allLineHandles(i).XData = NaN; %ignore warnings
%     allLineHandles(i).ZData = NaN; %ignore warnings
% end
% axis off
% figH.Position=[5 5 20 5];
% 
% 
% exportgraphics(gcf,fullfile("C:\G\Academic\University\Ph.D (leuven)\2024\2.15 MSSP paper\Matlab plots for paper\Pdfs"...
%     ,strcat('Figure_',"force_and_rpm_profile_Legend",string(datetime('now','Format','yyyyMMdd_HHmmss')),'.pdf')),'ContentType', 'vector');
% % %% Test with Nathan's function
% % fig1="C:\G\Academic\University\Ph.D (leuven)\2024\2.15 MSSP paper\Matlab plots for paper\Figs\force_and_rpm_profile.fig";
% % Figure_Styling_Iman_MSSP(fig1,...
% %     General_ShowFigure='visible',...
% %     General_SavePDF="TEST1",...
% %     General_SavePath="C:\G\Academic\University\Ph.D (leuven)\2024\2.15 MSSP paper\Matlab plots for paper\Pdfs",...
% %     SizeAndPos_heightCm=6,...
% %     SizeAndPos_widthCm=12,...
% %     Legend_OnOff="on",...
% %     Legend_Strings=["Force","Shaft speed"],...
% %     Legend_Location="southeast",...
% %     Axis_YLim=[],...
% %     Axis_XLim=[0 202],...
% %     Line_style=["-","-"],...
% %     Line_width=[1 1 1],...
% %     Line_marker=["^","o"],...
% %     Line_markerFreqRatio=25);
% % qq1f=gcf;
% % qq1ch=qq1f.Children;
% % qq2=figure('WindowState','maximized');
% % 
% % % qq3=sizedTile(qq2,scale=1,width=12,ratio=6/12);
% % 
% % 
% % t = tiledlayout(1,1,'Padding','tight','Parent',qq2);
% % h1=copyobj(qq1ch,t);
% % pause(0.5);
% % t.Units = 'centimeters';
% % f.Units = 'centimeters';
% % % width = params.width / params.scale;
% % % height = width / params.ratio;
% % width=12;height=6;
% % 
% % left = (t.Position(3) - width)/2;
% % bot = (t.Position(4) - height)/2;
% % t.OuterPosition = [left bot width height];
% % nexttile
% % axes
% % 
% % exportgraphics(gcf,fullfile("C:\G\Academic\University\Ph.D (leuven)\2024\2.15 MSSP paper\Matlab plots for paper\Pdfs"...
% %     ,strcat('Figure_',"test2Nathan",string(datetime('now','Format','yyyyMMdd_HHmmss')),'.pdf')),'ContentType', 'vector');
% %% Base MAC
% fig2="C:\G\Academic\University\Ph.D (leuven)\2024\2.15 MSSP paper\Matlab plots for paper\Figs\Base_MAC.fig";
% Figure_Styling_Iman_MSSP(fig2,...
%     General_ShowFigure='visible',...
%     General_SavePDF="",...
%     General_SavePath="C:\G\Academic\University\Ph.D (leuven)\2024\2.15 MSSP paper\Matlab plots for paper\Pdfs",...
%     SizeAndPos_heightCm=6*0.8,...
%     SizeAndPos_widthCm=7.5*0.8,...
%     Legend_OnOff="off",...
%     Legend_Strings=[],...
%     Legend_Location="southeast",...
%     Axis_YLim=[],...
%     Axis_XLim=[],...
%     Line_style=[],...
%     Line_width=[],...
%     Line_marker=[],...
%     Line_markerFreqRatio=25, ...
%     Axis_XminorTick="off",Axis_YminorTick="off",Axis_XGrid="off",Axis_YGrid="off",Axis_Box="on");
% colorbar
% exportgraphics(gcf,fullfile("C:\G\Academic\University\Ph.D (leuven)\2024\2.15 MSSP paper\Matlab plots for paper\Pdfs"...
%     ,strcat('Figure_',"Base_MAC",string(datetime('now','Format','yyyyMMdd_HHmmss')),'.pdf')),'ContentType', 'vector');
% %% Cap MAC
% fig3="C:\G\Academic\University\Ph.D (leuven)\2024\2.15 MSSP paper\Matlab plots for paper\Figs\Cap_MAC.fig";
% Figure_Styling_Iman_MSSP(fig3,...
%     General_ShowFigure='visible',...
%     General_SavePDF="",...
%     General_SavePath="C:\G\Academic\University\Ph.D (leuven)\2024\2.15 MSSP paper\Matlab plots for paper\Pdfs",...
%     SizeAndPos_heightCm=6*0.95,...
%     SizeAndPos_widthCm=7.5*0.95,...
%     Legend_OnOff="off",...
%     Legend_Strings=[],...
%     Legend_Location="southeast",...
%     Axis_YLim=[],...
%     Axis_XLim=[],...
%     Line_style=[],...
%     Line_width=[],...
%     Line_marker=[],...
%     Line_markerFreqRatio=25, ...
%     Axis_XminorTick="off",Axis_YminorTick="off",Axis_XGrid="off",Axis_YGrid="off",Axis_Box="on");
% colorbar
% exportgraphics(gcf,fullfile("C:\G\Academic\University\Ph.D (leuven)\2024\2.15 MSSP paper\Matlab plots for paper\Pdfs"...
%     ,strcat('Figure_',"Cap_MAC",string(datetime('now','Format','yyyyMMdd_HHmmss')),'.pdf')),'ContentType', 'vector');
% %% Assembled MAC
% fig4="C:\G\Academic\University\Ph.D (leuven)\2024\2.15 MSSP paper\Matlab plots for paper\Figs\Assembled_MAC.fig";
% Figure_Styling_Iman_MSSP(fig4,...
%     General_ShowFigure='visible',...
%     General_SavePDF="",...
%     General_SavePath="C:\G\Academic\University\Ph.D (leuven)\2024\2.15 MSSP paper\Matlab plots for paper\Pdfs",...
%     SizeAndPos_heightCm=6*0.8,... %%%9 for FM poster
%     SizeAndPos_widthCm=7.5*0.8,... %%%11.5 for FM poster
%     Legend_FontSize=10,...%%%25 for FM poster 
%     TitleLabel_LabelFontSize=10,... %%%25 for FM poster 
%     Axis_FontSize=10,... %%%25 for FM poster 
%     Legend_OnOff="off",...
%     Legend_Strings=[],...
%     Legend_Location="southeast",...
%     Axis_YLim=[],...
%     Axis_XLim=[],...
%     Line_style=[],...
%     Line_width=[],...
%     Line_marker=[],...
%     Line_markerFreqRatio=25, ...
%     Axis_XminorTick="off",Axis_YminorTick="off",Axis_XGrid="off",Axis_YGrid="off",Axis_Box="on");
% colorbar
% exportgraphics(gcf,fullfile("C:\G\Academic\University\Ph.D (leuven)\2024\2.15 MSSP paper\Matlab plots for paper\Pdfs"...
%     ,strcat('Figure_',"Assembled_MAC",string(datetime('now','Format','yyyyMMdd_HHmmss')),'.pdf')),'ContentType', 'vector');
% %% Figures of strain response forward simulation 
% close all;
% strainRespFigHeight=4;
% strainRespFigWidth=8;
% TextFontSize=10;
% sizeAndPosOfText=[0.75 0.8 0.09 0.1];
% Line_markers1=["none","none"];
% Line_color1=parula80(2);
% YlabelText="Strain [\mum/m]";
% XlabelText="Time [s]";
% 
% 
% fig6="C:\G\Academic\University\Ph.D (leuven)\2024\2.15 MSSP paper\Matlab plots for paper\Figs\x110x3AFL.fig";
% Figure_Styling_Iman_MSSP(fig6,...
%     General_ShowFigure='visible',...
%     General_SavePDF="",...
%     General_SavePath="C:\G\Academic\University\Ph.D (leuven)\2024\2.15 MSSP paper\Matlab plots for paper\Pdfs",...
%     SizeAndPos_heightCm=strainRespFigHeight,...
%     SizeAndPos_widthCm=strainRespFigWidth,...
%     Legend_Strings=["Measurement","Forward model"],...
%     Legend_Location="southeast",...
%     Legend_OnOff="off",...
%     Legend_Orientation="horizontal",...
%     TitleLabel_XlabelText=XlabelText,...
%     TitleLabel_YlabelText=YlabelText,...
%     Axis_YLim=[],...
%     Axis_XLim=[],...
%     Line_style=["-","-"],...
%     Line_width=[1 1 1],...
%     Line_color=Line_color1,...
%     Line_marker=Line_markers1,...
%     Line_markerFreqRatio=600);
% annotation("textbox",sizeAndPosOfText,String="FL",FontName="Times New Roman",FontSize=TextFontSize,Margin=1,HorizontalAlignment="center");
% exportgraphics(gcf,fullfile("C:\G\Academic\University\Ph.D (leuven)\2024\2.15 MSSP paper\Matlab plots for paper\Pdfs"...
%     ,strcat('Figure_',"SG_FL",string(datetime('now','Format','yyyyMMdd_HHmmss')),'.pdf')),'ContentType', 'vector');
% 
% fig7="C:\G\Academic\University\Ph.D (leuven)\2024\2.15 MSSP paper\Matlab plots for paper\Figs\x120x3AFM.fig";
% Figure_Styling_Iman_MSSP(fig7,...
%     General_ShowFigure='visible',...
%     General_SavePDF="",...
%     General_SavePath="C:\G\Academic\University\Ph.D (leuven)\2024\2.15 MSSP paper\Matlab plots for paper\Pdfs",...
%     SizeAndPos_heightCm=strainRespFigHeight,...
%     SizeAndPos_widthCm=strainRespFigWidth,...
%     Legend_Strings=["Measurement","Forward model"],...
%     Legend_Location="southeast",...
%     Legend_OnOff="off",...
%     Legend_Orientation="horizontal",...
%     TitleLabel_XlabelText=XlabelText,...
%     TitleLabel_YlabelText=YlabelText,...
%     Axis_YLim=[],...
%     Axis_XLim=[],...
%     Line_style=["-","-"],...
%     Line_width=[1 1 1],...
%     Line_color=Line_color1,...
%     Line_marker=Line_markers1,...
%     Line_markerFreqRatio=600);
% annotation("textbox",sizeAndPosOfText,String="FM",FontName="Times New Roman",FontSize=TextFontSize,Margin=1,HorizontalAlignment="center");
% exportgraphics(gcf,fullfile("C:\G\Academic\University\Ph.D (leuven)\2024\2.15 MSSP paper\Matlab plots for paper\Pdfs"...
%     ,strcat('Figure_',"SG_FM",string(datetime('now','Format','yyyyMMdd_HHmmss')),'.pdf')),'ContentType', 'vector');
% 
% fig8="C:\G\Academic\University\Ph.D (leuven)\2024\2.15 MSSP paper\Matlab plots for paper\Figs\x130x3AFR.fig";
% Figure_Styling_Iman_MSSP(fig8,...
%     General_ShowFigure='visible',...
%     General_SavePDF="",...
%     General_SavePath="C:\G\Academic\University\Ph.D (leuven)\2024\2.15 MSSP paper\Matlab plots for paper\Pdfs",...
%     SizeAndPos_heightCm=strainRespFigHeight,...
%     SizeAndPos_widthCm=strainRespFigWidth,...
%     Legend_Strings=["Measurement","Forward model"],...
%     Legend_Location="southeast",...
%     Legend_OnOff="off",...
%     Legend_Orientation="horizontal",...
%     TitleLabel_XlabelText=XlabelText,...
%     TitleLabel_YlabelText=YlabelText,...
%     Axis_YLim=[],...
%     Axis_XLim=[],...
%     Line_style=["-","-"],...
%     Line_width=[1 1 1],...
%     Line_color=Line_color1,...
%     Line_marker=Line_markers1,...
%     Line_markerFreqRatio=600);
% annotation("textbox",sizeAndPosOfText,String="FR",FontName="Times New Roman",FontSize=TextFontSize,Margin=1,HorizontalAlignment="center");
% exportgraphics(gcf,fullfile("C:\G\Academic\University\Ph.D (leuven)\2024\2.15 MSSP paper\Matlab plots for paper\Pdfs"...
%     ,strcat('Figure_',"SG_FR",string(datetime('now','Format','yyyyMMdd_HHmmss')),'.pdf')),'ContentType', 'vector');
% 
% fig9="C:\G\Academic\University\Ph.D (leuven)\2024\2.15 MSSP paper\Matlab plots for paper\Figs\x140x3ABL.fig";
% Figure_Styling_Iman_MSSP(fig9,...
%     General_ShowFigure='visible',...
%     General_SavePDF="",...
%     General_SavePath="C:\G\Academic\University\Ph.D (leuven)\2024\2.15 MSSP paper\Matlab plots for paper\Pdfs",...
%     SizeAndPos_heightCm=strainRespFigHeight,...
%     SizeAndPos_widthCm=strainRespFigWidth,...
%     Legend_Strings=["Measurement","Forward model"],...
%     Legend_Location="southeast",...
%     Legend_OnOff="off",...
%     Legend_Orientation="horizontal",...
%     TitleLabel_XlabelText=XlabelText,...
%     TitleLabel_YlabelText=YlabelText,...
%     Axis_YLim=[],...
%     Axis_XLim=[],...
%     Line_style=["-","-"],...
%     Line_width=[1 1 1],...
%     Line_color=Line_color1,...
%     Line_marker=Line_markers1,...
%     Line_markerFreqRatio=600);
% annotation("textbox",sizeAndPosOfText,String="BL",FontName="Times New Roman",FontSize=TextFontSize,Margin=1,HorizontalAlignment="center");
% exportgraphics(gcf,fullfile("C:\G\Academic\University\Ph.D (leuven)\2024\2.15 MSSP paper\Matlab plots for paper\Pdfs"...
%     ,strcat('Figure_',"SG_BL",string(datetime('now','Format','yyyyMMdd_HHmmss')),'.pdf')),'ContentType', 'vector');
% 
% fig10="C:\G\Academic\University\Ph.D (leuven)\2024\2.15 MSSP paper\Matlab plots for paper\Figs\x150x3ABM.fig";
% Figure_Styling_Iman_MSSP(fig10,...
%     General_ShowFigure='visible',...
%     General_SavePDF="",...
%     General_SavePath="C:\G\Academic\University\Ph.D (leuven)\2024\2.15 MSSP paper\Matlab plots for paper\Pdfs",...
%     SizeAndPos_heightCm=strainRespFigHeight,...
%     SizeAndPos_widthCm=strainRespFigWidth,...
%     Legend_Strings=["Measurement","Forward model"],...
%     Legend_Location="southeast",...
%     Legend_OnOff="off",...
%     Legend_Orientation="horizontal",...
%     TitleLabel_XlabelText=XlabelText,...
%     TitleLabel_YlabelText=YlabelText,...
%     Axis_YLim=[],...
%     Axis_XLim=[],...
%     Line_style=["-","-"],...
%     Line_width=[1 1 1],...
%     Line_color=Line_color1,...
%     Line_marker=Line_markers1,...
%     Line_markerFreqRatio=600);
% annotation("textbox",sizeAndPosOfText,String="BM",FontName="Times New Roman",FontSize=TextFontSize,Margin=1,HorizontalAlignment="center");
% exportgraphics(gcf,fullfile("C:\G\Academic\University\Ph.D (leuven)\2024\2.15 MSSP paper\Matlab plots for paper\Pdfs"...
%     ,strcat('Figure_',"SG_BM",string(datetime('now','Format','yyyyMMdd_HHmmss')),'.pdf')),'ContentType', 'vector');
% 
% fig11="C:\G\Academic\University\Ph.D (leuven)\2024\2.15 MSSP paper\Matlab plots for paper\Figs\x160x3ABR.fig";
% Figure_Styling_Iman_MSSP(fig11,...
%     General_ShowFigure='visible',...
%     General_SavePDF="",...
%     General_SavePath="C:\G\Academic\University\Ph.D (leuven)\2024\2.15 MSSP paper\Matlab plots for paper\Pdfs",...
%     SizeAndPos_heightCm=strainRespFigHeight,...
%     SizeAndPos_widthCm=strainRespFigWidth,...
%     Legend_Strings=["Measurement","Forward model"],...
%     Legend_Location="southeast",...
%     Legend_OnOff="off",...
%     Legend_Orientation="horizontal",...
%     TitleLabel_XlabelText=XlabelText,...
%     TitleLabel_YlabelText=YlabelText,...
%     Axis_YLim=[],...
%     Axis_XLim=[],...
%     Line_style=["-","-"],...
%     Line_width=[1 1 1],...
%     Line_color=Line_color1,...
%     Line_marker=Line_markers1,...
%     Line_markerFreqRatio=600);
% annotation("textbox",sizeAndPosOfText,String="BR",FontName="Times New Roman",FontSize=TextFontSize,Margin=1,HorizontalAlignment="center");
% exportgraphics(gcf,fullfile("C:\G\Academic\University\Ph.D (leuven)\2024\2.15 MSSP paper\Matlab plots for paper\Pdfs"...
%     ,strcat('Figure_',"SG_BR",string(datetime('now','Format','yyyyMMdd_HHmmss')),'.pdf')),'ContentType', 'vector');
% 
% %% To export the legend 
% fig11="C:\G\Academic\University\Ph.D (leuven)\2024\2.15 MSSP paper\Matlab plots for paper\Figs\x160x3ABR.fig";
% Figure_Styling_Iman_MSSP(fig11,...
%     General_ShowFigure='visible',...
%     General_SavePDF="",...
%     General_SavePath="C:\G\Academic\University\Ph.D (leuven)\2024\2.15 MSSP paper\Matlab plots for paper\Pdfs",...
%     SizeAndPos_heightCm=strainRespFigHeight,...
%     SizeAndPos_widthCm=strainRespFigWidth+5,...
%     Legend_Strings=["Measurement","Forward model"],...
%     Legend_Location="southeast",...
%     Legend_OnOff="on",...
%     Legend_Orientation="horizontal",...
%     TitleLabel_XlabelText="Time / s",...
%     TitleLabel_YlabelText="Strain / (mm/mm)",...
%     Axis_YLim=[],...
%     Axis_XLim=[],...
%     Line_style=["-","-"],...
%     Line_width=[1 1 1],...
%     Line_color=Line_color1,...
%     Line_marker=Line_markers1,...
%     Line_markerFreqRatio=600);
% 
% legHandle=legend();
% figHandle=gcf;
% allLineHandles = findall(gcf, 'type', 'line');
% 
% for i = 1:length(allLineHandles)
%     allLineHandles(i).XData = NaN; %ignore warnings
% end
% axis off
% legHandle.Units = 'pixels';
% exportgraphics(figHandle,fullfile("C:\G\Academic\University\Ph.D (leuven)\2024\2.15 MSSP paper\Matlab plots for paper\Pdfs"...
%     ,strcat('Figure_',"SG_legend",string(datetime('now','Format','yyyyMMdd_HHmmss')),'.pdf')),'ContentType', 'vector');
% %% Num example BC identification
% close all
% fig12="C:\G\Academic\University\Ph.D (leuven)\2024\2.15 MSSP paper\Matlab plots for paper\Figs\FMposter_NumEx_IdentifiedBC.fig";
% Figure_Styling_Iman_MSSP(fig12,...
%     General_ShowFigure='visible',...
%     General_SavePDF="",...
%     General_SavePath="C:\G\Academic\University\Ph.D (leuven)\2024\2.15 MSSP paper\Matlab plots for paper\Pdfs",...
%     SizeAndPos_heightCm=7,... %%%12.54 for FM poster 
%     SizeAndPos_widthCm=15,... %%%25 for FM poster
%     Legend_FontSize=10,...%%%25 for FM poster 
%     TitleLabel_LabelFontSize=10,... %%%25 for FM poster 
%     Axis_FontSize=10,... %%%25 for FM poster 
%     Legend_OnOff="ff",...
%     Legend_Strings=["Force","Shaft speed"],...
%     Legend_Location="southeast",...
%     TitleLabel_XlabelText="X [mm]",...
%     TitleLabel_YlabelText="Z [mm]",...
%     Axis_YLim=[],...
%     Axis_XLim=[],...
%     Line_style=["-","-"],...
%     Line_width=[1 1 1],...
%     Line_marker=["^","o"],...
%     Line_markerFreqRatio=25);
% % colorbar;
% figfig=gcf;
% ax=gca;
% ax.ZLabel.String='log_{10}({DV}_{s})';
% zlim([-6 3]); %(-4.9 and 1.7 are min and max)
% scatterObj = findobj(ax, 'Type', 'Scatter');
% scatterObj.Marker = "o"; % 
% scatterObj.MarkerFaceColor="flat";
% min_clim=min(scatterObj.ZData);
% max_clim=max(scatterObj.ZData);
% % colormap hot
% % view(-90,90)
% 
% 
% exportgraphics(figfig,fullfile("C:\G\Academic\University\Ph.D (leuven)\2024\2.15 MSSP paper\Matlab plots for paper\Pdfs"...
%     ,strcat('Figure_',"BC_NumCheck_Identified",string(datetime('now','Format','yyyyMMdd_HHmmss')),'.pdf')),'ContentType', 'vector');
% 
% fig13="C:\G\Academic\University\Ph.D (leuven)\2024\2.15 MSSP paper\Matlab plots for paper\Figs\FMposter_NumEx_InitialBC.fig";
% Figure_Styling_Iman_MSSP(fig13,...
%     General_ShowFigure='visible',...
%     General_SavePDF="",...
%     General_SavePath="C:\G\Academic\University\Ph.D (leuven)\2024\2.15 MSSP paper\Matlab plots for paper\Pdfs",...
%     SizeAndPos_heightCm=7,... %%%12.54 for FM poster 
%     SizeAndPos_widthCm=15,... %%%25 for FM poster
%     Legend_FontSize=10,...%%%25 for FM poster 
%     TitleLabel_LabelFontSize=10,... %%%25 for FM poster 
%     Axis_FontSize=10,... %%%25 for FM poster 
%     Legend_OnOff="ff",...
%     Legend_Strings=["Force","Shaft speed"],...
%     Legend_Location="southeast",...
%     TitleLabel_XlabelText="X [mm]",...
%     TitleLabel_YlabelText="Z [mm]",...
%     Axis_YLim=[],...
%     Axis_XLim=[],...
%     Line_style=["-","-"],...
%     Line_width=[1 1 1],...
%     Line_marker=["^","o"],...
%     Line_markerFreqRatio=25);
% % colorbar('southoutside');
% zlim([-6 3]); %(-4.9 and 1.7 are min and max)
% clim([min_clim max_clim])
% % colormap hot
% figfig=gcf;
% ax=gca;
% ax.ZLabel.String='log_{10}({DV}_{s})';
% scatterObj = findobj(ax, 'Type', 'Scatter');
% scatterObj.Marker = "o"; % Change the marker to square
% scatterObj.MarkerFaceColor="flat";
% % view(-90,90)
% 
% exportgraphics(figfig,fullfile("C:\G\Academic\University\Ph.D (leuven)\2024\2.15 MSSP paper\Matlab plots for paper\Pdfs"...
%     ,strcat('Figure_',"BC_NumCheck_Initial",string(datetime('now','Format','yyyyMMdd_HHmmss')),'.pdf')),'ContentType', 'vector');
% 
% qq1=colorbar('southoutside');
% % qq1.Title.String='log_{10} of scaled design variable';
% allLineHandles = findall(gcf, 'type','scatter');
% for i = 1:length(allLineHandles)
%     allLineHandles(i).XData = NaN; %ignore warnings
%     allLineHandles(i).ZData = NaN; %ignore warnings
% end
% axis off
% 
% exportgraphics(figfig,fullfile("C:\G\Academic\University\Ph.D (leuven)\2024\2.15 MSSP paper\Matlab plots for paper\Pdfs"...
%     ,strcat('Figure_',"BC_NumCheck_Colorbar",string(datetime('now','Format','yyyyMMdd_HHmmss')),'.pdf')),'ContentType', 'vector');
% %% AKF result - force, force_zoomed, force_freq
% %Force
% close all
% Line_color1=parula80(2);
% 
% fig14="C:\G\Academic\University\Ph.D (leuven)\2024\2.15 MSSP paper\Matlab plots for paper\Figs\AKF_Force.fig";
% Figure_Styling_Iman_MSSP(fig14,...
%     General_ShowFigure='visible',...
%     General_SavePDF="",...
%     General_SavePath="C:\G\Academic\University\Ph.D (leuven)\2024\2.15 MSSP paper\Matlab plots for paper\Pdfs",...
%     SizeAndPos_heightCm=6,... %%%15.54 for FM poster 
%     SizeAndPos_widthCm=15.5,... %%%28 for FM poster 
%     Legend_FontSize=10,...%%%25 for FM poster 
%     TitleLabel_LabelFontSize=10,... %%%25 for FM poster 
%     Axis_FontSize=10,... %%%25 for FM poster
%     Legend_Strings=["Measurement","AKF"],...
%     Legend_Location="southeast",...
%     Legend_OnOff="on",...
%     Legend_Orientation="horizontal",...
%     TitleLabel_XlabelText="Time [s]",...
%     TitleLabel_YlabelText="Force [kN]",...
%     Axis_YLim=[],...
%     Axis_XLim=[0 200],...
%     Line_style=["-","-"],...
%     Line_width=[1 1 1],...
%     Line_color=Line_color1,...
%     Line_marker=["none","none"],...
%     Line_markerFreqRatio=600);
% figHandle=gcf;
% axHandle=figHandle.CurrentAxes;
% h=axHandle.Children;
% for i=1:length(h)
%     h(i,1).XData=h(i,1).XData-h(i,1).XData(1);
% end
% %%%%% An effort to try to add on the right axis error value
% allLineHandles = findall(axHandle, 'type','Line');
% pp1=(allLineHandles(1).YData-allLineHandles(2).YData);
% % pp2=smooth(pp1,5000);
% pp2=smooth(pp1,100000);
% %%%%figure;plot(allLineHandles(2).XData,pp2)
% % dt=allLineHandles(2).XData(2)-allLineHandles(2).XData(1); %%Butterworth
% % [bb,aa]=butter(2,2*30*dt,"low");
% % pp3=filtfilt(bb,aa,pp1);
% % figure;plot(allLineHandles(2).XData,pp3)
% % yyaxis right
% ee1=plot(allLineHandles(2).XData,pp2);
% set(ee1, 'LineStyle', "-", 'Color', 0.5*[Line_color1(1,:)+Line_color1(2,:)],'LineWidth', 2);
% axHandle.Legend.String{3}='Error (smoothed)';
% %%%%%
% % pp1=(pp2')./allLineHandles(2).YData;
% 
% exportgraphics(figHandle,fullfile("C:\G\Academic\University\Ph.D (leuven)\2024\2.15 MSSP paper\Matlab plots for paper\Pdfs"...
%     ,strcat('Figure_',"AKF_Force",string(datetime('now','Format','yyyyMMdd_HHmmss')),'.pdf')),'ContentType', 'vector');
% 
% % %Force_zoomed
% % % Axis_XLim=[746.05-745.0000 746.6-745.0000],... %This is the normal zoom
% % % Axis_XLim=[746.15-745.0000 746.20-745.0000],... %EVEN more zoom
% % Figure_Styling_Iman_MSSP(fig14,...
% %     General_ShowFigure='visible',...
% %     General_SavePDF="",...
% %     General_SavePath="C:\G\Academic\University\Ph.D (leuven)\2024\2.15 MSSP paper\Matlab plots for paper\Pdfs",...
% %     SizeAndPos_heightCm=4,... %%%6 for FM poster 
% %     SizeAndPos_widthCm=7.5,... %%%12 for FM poster 
% %     Legend_FontSize=10,...%%%25 for FM poster 
% %     TitleLabel_LabelFontSize=10,... %%%25 for FM poster 
% %     Axis_FontSize=10,... %%%25 for FM poster
% %     Legend_Strings=["Measurement","AKF"],...
% %     Legend_Location="southeast",...
% %     Legend_OnOff="off",...
% %     Legend_Orientation="horizontal",...
% %     TitleLabel_XlabelText="Time [s]",...
% %     TitleLabel_YlabelText="Force [kN]",...
% %     Axis_YLim=[],...
% %     Axis_XLim=[746.4-745.0000 746.6-745.0000],... %EVEN more zoom
% %     Line_style=["-","-"],...
% %     Line_width=[1 1 1],...
% %     Line_color=Line_color1,...
% %     Line_marker=["none","none"],...
% %     Line_markerFreqRatio=600);
% % figHandle=gcf;
% % axHandle=figHandle.CurrentAxes;
% % h=axHandle.Children;
% % for i=1:length(h)
% %     h(i,1).XData=h(i,1).XData-h(i,1).XData(1);
% % end
% % 
% % exportgraphics(figHandle,fullfile("C:\G\Academic\University\Ph.D (leuven)\2024\2.15 MSSP paper\Matlab plots for paper\Pdfs"...
% %     ,strcat('Figure_',"AKF_FZoomed",string(datetime('now','Format','yyyyMMdd_HHmmss')),'.pdf')),'ContentType', 'vector');
% 
% %Force_zoomed2
% Figure_Styling_Iman_MSSP(figHandle,...
%     General_ShowFigure='visible',...
%     General_SavePDF="",...
%     General_SavePath="C:\G\Academic\University\Ph.D (leuven)\2024\2.15 MSSP paper\Matlab plots for paper\Pdfs",...
%     SizeAndPos_heightCm=4,... %%%6 for FM poster 
%     SizeAndPos_widthCm=7.5,... %%%12 for FM poster 
%     Legend_FontSize=10,...%%%25 for FM poster 
%     TitleLabel_LabelFontSize=10,... %%%25 for FM poster 
%     Axis_FontSize=10,... %%%25 for FM poster
%     Legend_Strings=["Measurement","AKF"],...
%     Legend_Location="southeast",...
%     Legend_OnOff="off",...
%     Legend_Orientation="horizontal",...
%     TitleLabel_XlabelText="Time [s]",...
%     TitleLabel_YlabelText="Force [kN]",...
%     Axis_YLim=[],...
%     Axis_XLim=[746.4699-745.0000 746.5205-745.0000],... %EVEN more zoom
%     Line_style=["-","-"],...
%     Line_width=[1 1 1],...
%     Line_color=Line_color1,...
%     Line_marker=["none","none"],...
%     Line_markerFreqRatio=600);
% q1=gca;
% q1.XTick=1.47:0.01:1.52;
% % xlim([836.4799-745.0000 836.521-745.0000])
% exportgraphics(figHandle,fullfile("C:\G\Academic\University\Ph.D (leuven)\2024\2.15 MSSP paper\Matlab plots for paper\Pdfs"...
%     ,strcat('Figure_',"AKF_FZoomedExtra",string(datetime('now','Format','yyyyMMdd_HHmmss')),'.pdf')),'ContentType', 'vector');
% 
% %Force_zoomed3
% % Axis_XLim=[746.05-745.0000 746.6-745.0000],... %This is the normal zoom
% % Axis_XLim=[746.15-745.0000 746.20-745.0000],... %EVEN more zoom
% Figure_Styling_Iman_MSSP(fig14,...
%     General_ShowFigure='visible',...
%     General_SavePDF="",...
%     General_SavePath="C:\G\Academic\University\Ph.D (leuven)\2024\2.15 MSSP paper\Matlab plots for paper\Pdfs",...
%     SizeAndPos_heightCm=4,... %%%6 for FM poster 
%     SizeAndPos_widthCm=7.5,... %%%12 for FM poster 
%     Legend_FontSize=10,...%%%25 for FM poster 
%     TitleLabel_LabelFontSize=10,... %%%25 for FM poster 
%     Axis_FontSize=10,... %%%25 for FM poster
%     Legend_Strings=["Measurement","AKF"],...
%     Legend_Location="southeast",...
%     Legend_OnOff="off",...
%     Legend_Orientation="horizontal",...
%     TitleLabel_XlabelText="Time [s]",...
%     TitleLabel_YlabelText="Force [kN]",...
%     Axis_YLim=[],...
%     Axis_XLim=[836.4799-745.0000 836.521-745.0000],... %EVEN more zoom
%     Line_style=["-","-"],...
%     Line_width=[1 1 1],...
%     Line_color=Line_color1,...
%     Line_marker=["none","none"],...
%     Line_markerFreqRatio=600);
% figHandle=gcf;
% axHandle=figHandle.CurrentAxes;
% h=axHandle.Children;
% for i=1:length(h)
%     h(i,1).XData=h(i,1).XData-h(i,1).XData(1);
% end
% 
% exportgraphics(figHandle,fullfile("C:\G\Academic\University\Ph.D (leuven)\2024\2.15 MSSP paper\Matlab plots for paper\Pdfs"...
%     ,strcat('Figure_',"AKF_FZoomed3_higherror",string(datetime('now','Format','yyyyMMdd_HHmmss')),'.pdf')),'ContentType', 'vector');
% 
% 
% %Force_freq
% fig15="C:\G\Academic\University\Ph.D (leuven)\2024\2.15 MSSP paper\Matlab plots for paper\Figs\AKF_Force_FreqDomain.fig";
% Figure_Styling_Iman_MSSP(fig15,...
%     General_ShowFigure='visible',...
%     General_SavePDF="",...
%     General_SavePath="C:\G\Academic\University\Ph.D (leuven)\2024\2.15 MSSP paper\Matlab plots for paper\Pdfs",...
%     SizeAndPos_heightCm=6,... %%%15.54 for FM poster
%     SizeAndPos_widthCm=16.5,... %%%28 for FM poster
%     Legend_FontSize=10,...%%%25 for FM poster 
%     TitleLabel_LabelFontSize=10,... %%%25 for FM poster 
%     Axis_FontSize=10,... %%%25 for FM poster
%     Legend_Strings=["Measurement","AKF"],...
%     Legend_Location="northeast",...
%     Legend_OnOff="on",...
%     Legend_Orientation="horizontal",...
%     TitleLabel_XlabelText="Frequency [Hz]",...
%     TitleLabel_YlabelText="log_{10}(Force) [kN]",...
%     Axis_YLim=[],...
%     Axis_XLim=[0 340],...
%     Line_style=["-","-"],...
%     Line_width=[1 1 1],...
%     Line_color=Line_color1,...
%     Line_marker=["none","none"],...
%     Line_markerFreqRatio=600);
% 
% xlim([0 10000])
% figHandle=gcf;
% axHandle=figHandle.CurrentAxes;
% axHandle.XScale='log';
% axHandle.Legend.Location='southwest';
% 
% dt = findobj(gca(),'Type','DataTip');
% delete(dt);
% 
% exportgraphics(figHandle,fullfile("C:\G\Academic\University\Ph.D (leuven)\2024\2.15 MSSP paper\Matlab plots for paper\Pdfs"...
%     ,strcat('Figure_',"AKF_F_freq_loglog",string(datetime('now','Format','yyyyMMdd_HHmmss')),'.pdf')),'ContentType', 'vector');
% 
% 
% %first freq section
% fig15="C:\G\Academic\University\Ph.D (leuven)\2024\2.15 MSSP paper\Matlab plots for paper\Figs\AKF_Force_FreqDomain.fig";
% Figure_Styling_Iman_MSSP(fig15,...
%     General_ShowFigure='visible',...
%     General_SavePDF="",...
%     General_SavePath="C:\G\Academic\University\Ph.D (leuven)\2024\2.15 MSSP paper\Matlab plots for paper\Pdfs",...
%     SizeAndPos_heightCm=5,... %%%15.54 for FM poster
%     SizeAndPos_widthCm=8,... %%%28 for FM poster
%     Legend_FontSize=10,...%%%25 for FM poster 
%     TitleLabel_LabelFontSize=10,... %%%25 for FM poster 
%     Axis_FontSize=10,... %%%25 for FM poster
%     Legend_Strings=["Measurement","AKF"],...
%     Legend_Location="northeast",...
%     Legend_OnOff="on",...
%     Legend_Orientation="horizontal",...
%     TitleLabel_XlabelText="Frequency [Hz]",...
%     TitleLabel_YlabelText="log_{10}(Force) [kN]",...
%     Axis_YLim=[],...
%     Axis_XLim=[0 26000],...
%     Line_style=["-","-"],...
%     Line_width=[1 1 1],...
%     Line_color=Line_color1,...
%     Line_marker=["none","none"],...
%     Line_markerFreqRatio=600);
% 
% figHandle=gcf;
% axHandle=figHandle.CurrentAxes;
% % axHandle.XScale='log';
% 
% dt = findobj(gca(),'Type','DataTip');
% delete(dt);
% xlim([75 85])
% ylim([1e-5,3e-2])
% % xlim([155 165])
% axHandle.Legend.Visible='off';
% 
% exportgraphics(figHandle,fullfile("C:\G\Academic\University\Ph.D (leuven)\2024\2.15 MSSP paper\Matlab plots for paper\Pdfs"...
%     ,strcat('Figure_',"AKF_F_freq_75_85",string(datetime('now','Format','yyyyMMdd_HHmmss')),'.pdf')),'ContentType', 'vector');
% 
% 
% 
% %second freq section
% fig15="C:\G\Academic\University\Ph.D (leuven)\2024\2.15 MSSP paper\Matlab plots for paper\Figs\AKF_Force_FreqDomain.fig";
% Figure_Styling_Iman_MSSP(fig15,...
%     General_ShowFigure='visible',...
%     General_SavePDF="",...
%     General_SavePath="C:\G\Academic\University\Ph.D (leuven)\2024\2.15 MSSP paper\Matlab plots for paper\Pdfs",...
%     SizeAndPos_heightCm=5,... %%%15.54 for FM poster
%     SizeAndPos_widthCm=8,... %%%28 for FM poster
%     Legend_FontSize=10,...%%%25 for FM poster 
%     TitleLabel_LabelFontSize=10,... %%%25 for FM poster 
%     Axis_FontSize=10,... %%%25 for FM poster
%     Legend_Strings=["Measurement","AKF"],...
%     Legend_Location="northeast",...
%     Legend_OnOff="on",...
%     Legend_Orientation="horizontal",...
%     TitleLabel_XlabelText="Frequency [Hz]",...
%     TitleLabel_YlabelText="log_{10}(Force) [kN]",...
%     Axis_YLim=[],...
%     Axis_XLim=[0 26000],...
%     Line_style=["-","-"],...
%     Line_width=[1 1 1],...
%     Line_color=Line_color1,...
%     Line_marker=["none","none"],...
%     Line_markerFreqRatio=600);
% 
% figHandle=gcf;
% axHandle=figHandle.CurrentAxes;
% axHandle.XScale='log';
% 
% dt = findobj(gca(),'Type','DataTip');
% delete(dt);
% 
% allLineHandles = findall(axHandle, 'type','Line');
% pp1=allLineHandles(1).YData;
% pp2=allLineHandles(2).YData;
% % pp2=smooth(pp1,5000);
% pp1s=smooth(pp1,100);
% pp2s=smooth(pp2,100);
% %%%%figure;plot(allLineHandles(2).XData,pp2)
% % dt=allLineHandles(2).XData(2)-allLineHandles(2).XData(1); %%Butterworth
% % [bb,aa]=butter(2,2*30*dt,"low");
% % pp3=filtfilt(bb,aa,pp1);
% % figure;plot(allLineHandles(2).XData,pp3)
% % yyaxis right
% start_idx=201;
% ee1=plot(allLineHandles(2).XData(start_idx:end),pp1s(start_idx:end));
% ee2=plot(allLineHandles(2).XData(start_idx:end),pp2s(start_idx:end));
% set(ee1, 'LineStyle', "-", 'Color', 0.333*[Line_color1(1,:)+Line_color1(2,:)],'LineWidth', 3);
% set(ee2, 'LineStyle', "-", 'Color', 0.666*[Line_color1(1,:)+Line_color1(2,:)],'LineWidth', 3);
% xlim([400 430])
% axHandle.Legend.String{3}='AKF (smoothed)';
% axHandle.Legend.String{4}='Measurement (smoothed)';
% axHandle.Legend.Visible='off';
% 
% exportgraphics(figHandle,fullfile("C:\G\Academic\University\Ph.D (leuven)\2024\2.15 MSSP paper\Matlab plots for paper\Pdfs"...
%     ,strcat('Figure_',"AKF_F_freq_400_430",string(datetime('now','Format','yyyyMMdd_HHmmss')),'.pdf')),'ContentType', 'vector');
% 
% 
% 
% 
% %% Identified BC of the BH
% fig16="C:\G\Academic\University\Ph.D (leuven)\2024\2.15 MSSP paper\Matlab plots for paper\Figs\Identified_BC_BH.fig";
% Figure_Styling_Iman_MSSP(fig16,...
%     General_ShowFigure='visible',...
%     General_SavePDF="",...
%     General_SavePath="C:\G\Academic\University\Ph.D (leuven)\2024\2.15 MSSP paper\Matlab plots for paper\Pdfs",...
%     SizeAndPos_heightCm=7,...
%     SizeAndPos_widthCm=15,...
%     Legend_OnOff="ff",...
%     Legend_Strings=["Force","Shaft speed"],...
%     Legend_Location="southeast",...
%     TitleLabel_XlabelText="X [mm]",...
%     TitleLabel_YlabelText="Z [mm]",...
%     Axis_YLim=[],...
%     Axis_XLim=[],...
%     Line_style=["-","-"],...
%     Line_width=[1 1 1],...
%     Line_marker=["^","o"],...
%     Line_markerFreqRatio=25);
% % colorbar;
% figfig=gcf;
% ax=gca;
% ax.ZLabel.String='log_{10}({DV}_{s})';
% zlim([-8 6]); %(-7.6 and 5.1 are min and max)
% % zlim([-10 10]); %(-7.6 and 5.1 are min and max)
% scatterObj = findobj(ax, 'Type', 'Scatter');
% scatterObj.Marker = "o"; % 
% scatterObj.MarkerFaceColor="flat";
% min_clim=min(scatterObj.ZData);
% max_clim=max(scatterObj.ZData);
% 
% exportgraphics(figfig,fullfile("C:\G\Academic\University\Ph.D (leuven)\2024\2.15 MSSP paper\Matlab plots for paper\Pdfs"...
%     ,strcat('Figure_',"Identified_BC_BH",string(datetime('now','Format','yyyyMMdd_HHmmss')),'.pdf')),'ContentType', 'vector');
% 
% qq1=colorbar('southoutside');
% % qq1.Title.String='log_{10} of scaled design variable';
% allLineHandles = findall(gcf, 'type','scatter');
% for i = 1:length(allLineHandles)
%     allLineHandles(i).XData = NaN; %ignore warnings
%     allLineHandles(i).ZData = NaN; %ignore warnings
% end
% axis off
% 
% exportgraphics(figfig,fullfile("C:\G\Academic\University\Ph.D (leuven)\2024\2.15 MSSP paper\Matlab plots for paper\Pdfs"...
%     ,strcat('Figure_',"Identified_BC_BH_colorbar",string(datetime('now','Format','yyyyMMdd_HHmmss')),'.pdf')),'ContentType', 'vector');
% 
% %% Figs of strain response at the boundary
% fig17="C:\G\Academic\University\Ph.D (leuven)\2024\2.15 MSSP paper\Matlab plots for paper\Figs\VonMisesStrain_optimizedBC_MSSP.fig";
% Figure_Styling_Iman_MSSP(fig17,...
%     General_ShowFigure='visible',...
%     General_SavePDF="",...
%     General_SavePath="C:\G\Academic\University\Ph.D (leuven)\2024\2.15 MSSP paper\Matlab plots for paper\Pdfs",...
%     SizeAndPos_heightCm=4,...
%     SizeAndPos_widthCm=7.5,...
%     Legend_OnOff="off",...
%     Legend_Strings=[],...
%     Legend_Location="southeast",...
%     TitleLabel_XlabelText="X [mm]",...
%     TitleLabel_YlabelText="Z [mm]",...
%     Axis_YLim=[],...
%     Axis_XLim=[],...
%     Line_style=["-","-"],...
%     Line_width=[1 1 1],...
%     Line_marker=["^","o"],...
%     Line_markerFreqRatio=25,...
%     Axis_Box="off");
% q1=gca;
% q2=q1.Children;
% rotate(q2,[1 0 0],90,[0 0 0])
% view(-90,0)
% zlim([-60 -30])
% ylim([-65 0])
% q1.ZLabel.String="Y [mm]";
% q4=gcf;
% q5=q4.Children(2); %This one is the colorbar
% Colorbar_limits=q5.Limits;
% colorbar off
% q1.ZGrid="on";
% q1.YMinorTick="off";
% q1.ZMinorTick="off";
% q1.YTick=[-70,-65:15:0,0];
% q1.ZTick=-60:10:-30;
% pos1= get(q4, 'Position');
% q4.Position=[pos1(1),pos1(2),pos1(3),pos1(4)+0.5];
% 
% exportgraphics(q4,fullfile("C:\G\Academic\University\Ph.D (leuven)\2024\2.15 MSSP paper\Matlab plots for paper\Pdfs"...
%     ,strcat('Figure_',"VMStrain_optBC",string(datetime('now','Format','yyyyMMdd_HHmmss')),'.pdf')),'ContentType', 'image','Resolution',600);
% 
% 
% fig18="C:\G\Academic\University\Ph.D (leuven)\2024\2.15 MSSP paper\Matlab plots for paper\Figs\VonMisesStrain_RigidBottom_MSSP.fig";
% Figure_Styling_Iman_MSSP(fig18,...
%     General_ShowFigure='visible',...
%     General_SavePDF="",...
%     General_SavePath="C:\G\Academic\University\Ph.D (leuven)\2024\2.15 MSSP paper\Matlab plots for paper\Pdfs",...
%     SizeAndPos_heightCm=4,...
%     SizeAndPos_widthCm=7.5,...
%     Legend_OnOff="off",...
%     Legend_Strings=[],...
%     Legend_Location="southeast",...
%     TitleLabel_XlabelText="X [mm]",...
%     TitleLabel_YlabelText="Z [mm]",...
%     Axis_YLim=[],...
%     Axis_XLim=[],...
%     Line_style=["-","-"],...
%     Line_width=[1 1 1],...
%     Line_marker=["^","o"],...
%     Line_markerFreqRatio=25,...
%     Axis_Box="off");
% q1=gca;
% q2=q1.Children;
% rotate(q2,[1 0 0],90,[0 0 0])
% view(-90,0)
% zlim([-60 -30])
% ylim([-65 0])
% q1.ZLabel.String="Y [mm]";
% q4=gcf;
% q5=q4.Children(2); %This one is the colorbar
% q5.Limits=Colorbar_limits;
% colorbar off
% q1.ZGrid="on";
% q1.YMinorTick="off";
% q1.ZMinorTick="off";
% q1.YTick=[-70,-65:15:0,0];
% q1.ZTick=-60:10:-30;
% pos1= get(q4, 'Position');
% q4.Position=[pos1(1),pos1(2),pos1(3),pos1(4)+0.5];
% 
% exportgraphics(q4,fullfile("C:\G\Academic\University\Ph.D (leuven)\2024\2.15 MSSP paper\Matlab plots for paper\Pdfs"...
%     ,strcat('Figure_',"VMStrain_RigidBC",string(datetime('now','Format','yyyyMMdd_HHmmss')),'.pdf')),'ContentType', 'image','Resolution',600);
% 
% Figure_Styling_Iman_MSSP(gcf,...
%     General_ShowFigure='visible',...
%     General_SavePDF="",...
%     General_SavePath="C:\G\Academic\University\Ph.D (leuven)\2024\2.15 MSSP paper\Matlab plots for paper\Pdfs",...
%     SizeAndPos_heightCm=4,...
%     SizeAndPos_widthCm=7.5,...
%     Legend_OnOff="off",...
%     Legend_Strings=[],...
%     Legend_Location="southeast",...
%     TitleLabel_XlabelText="X [mm]",...
%     TitleLabel_YlabelText="Z [mm]",...
%     Axis_YLim=[],...
%     Axis_XLim=[],...
%     Line_style=["-","-"],...
%     Line_width=[1 1 1],...
%     Line_marker=["^","o"],...
%     Line_markerFreqRatio=25,...
%     Axis_Box="off");
% 
% qq1=colorbar('southoutside');
% % qq1.Title.String='log_{10} of scaled design variable';
% allLineHandles = findall(q4, 'type','scatter');
% for i = 1:length(allLineHandles)
%     allLineHandles(i).XData = NaN; %ignore warnings
%     allLineHandles(i).ZData = NaN; %ignore warnings
% end
% q5=q1.Children;
% q5.Faces=NaN;
% axis off
% 
% exportgraphics(q4,fullfile("C:\G\Academic\University\Ph.D (leuven)\2024\2.15 MSSP paper\Matlab plots for paper\Pdfs"...
%     ,strcat('Figure_',"VMStrain_Colorbar",string(datetime('now','Format','yyyyMMdd_HHmmss')),'.pdf')),'ContentType', 'vector');
% 
% 
